module.exports = {
    entryPoints: ['src'],
    entryPointStrategy : 'Expand',
    exclude : ['**/test/**/*', '**/*.spec.ts'],
    out: 'docs',
    sort : ['alphabetical'],
    readme: 'none',
    cleanOutputDir: true,
    includeVersion: true,
    excludeExternals: true,
    excludePrivate : true,
    disableSources: true,
    plugin: 'typedoc-plugin-markdown',
    hideBreadcrumbs: true,
}